In [1]:
import numpy as np
class1=np.random.randint(30,100,size=(54,4))
print(class1)

[[84 96 92 54]
 [58 66 39 52]
 [53 48 75 67]
 [63 56 61 54]
 [90 63 83 98]
 [37 97 55 69]
 [79 78 83 92]
 [46 43 42 39]
 [38 55 35 68]
 [39 86 53 92]
 [71 89 41 63]
 [85 60 54 64]
 [64 68 61 35]
 [63 93 38 32]
 [63 96 80 56]
 [55 86 39 63]
 [56 85 76 44]
 [58 73 84 59]
 [48 74 40 79]
 [40 56 41 79]
 [30 53 55 48]
 [80 72 47 33]
 [84 87 67 35]
 [88 54 48 60]
 [92 51 57 37]
 [41 75 39 77]
 [87 44 30 54]
 [95 72 51 32]
 [94 73 78 48]
 [78 64 50 90]
 [79 57 85 76]
 [72 41 37 32]
 [40 46 63 41]
 [62 86 73 84]
 [88 88 93 58]
 [99 93 50 40]
 [94 33 48 44]
 [98 81 37 49]
 [91 49 90 59]
 [46 42 99 81]
 [97 87 30 56]
 [76 87 58 47]
 [34 84 99 85]
 [47 73 68 80]
 [97 32 47 47]
 [93 67 86 39]
 [97 33 90 52]
 [96 77 75 40]
 [91 51 67 40]
 [97 50 79 88]
 [47 58 93 65]
 [86 86 44 48]
 [92 76 30 87]
 [79 66 49 61]]


In [2]:
pj=class1.mean(axis=0)[1]
print("第2门课的平均分; ",round(pj,2))

第2门课的平均分;  67.7


In [3]:
zf=class1.sum(axis=1)[2]
print("第3个同学的总分： ",zf)

第3个同学的总分：  243
