In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=np.random.randint(0,5,size=(10,10))
print('原数据'.center(50,'-'),'\n',data)
n=4
i=1+(data.shape[0]-4)
j=1+(data.shape[1]-4)
mid_data=np.lib.stride_tricks.as_strided(data,shape=(i,j,n,n),strides=data.strides+data.strides)
print('提取后的数据: '.center(50,'-'),'\n',mid_data)

-----------------------原数据------------------------ 
 [[2 0 0 2 0 4 4 2 2 1]
 [1 0 3 4 0 4 2 4 3 2]
 [1 3 3 4 3 0 1 4 4 4]
 [2 1 1 3 3 1 4 0 2 4]
 [2 4 3 3 1 1 2 4 0 4]
 [2 3 4 1 3 0 0 4 1 0]
 [4 4 0 1 2 0 1 0 1 4]
 [3 2 2 1 4 3 4 0 0 0]
 [0 1 2 2 2 3 3 3 2 4]
 [2 2 0 4 1 0 3 4 3 1]]
---------------------提取后的数据: --------------------- 
 [[[[2 0 0 2]
   [1 0 3 4]
   [1 3 3 4]
   [2 1 1 3]]

  [[0 0 2 0]
   [0 3 4 0]
   [3 3 4 3]
   [1 1 3 3]]

  [[0 2 0 4]
   [3 4 0 4]
   [3 4 3 0]
   [1 3 3 1]]

  [[2 0 4 4]
   [4 0 4 2]
   [4 3 0 1]
   [3 3 1 4]]

  [[0 4 4 2]
   [0 4 2 4]
   [3 0 1 4]
   [3 1 4 0]]

  [[4 4 2 2]
   [4 2 4 3]
   [0 1 4 4]
   [1 4 0 2]]

  [[4 2 2 1]
   [2 4 3 2]
   [1 4 4 4]
   [4 0 2 4]]]


 [[[1 0 3 4]
   [1 3 3 4]
   [2 1 1 3]
   [2 4 3 3]]

  [[0 3 4 0]
   [3 3 4 3]
   [1 1 3 3]
   [4 3 3 1]]

  [[3 4 0 4]
   [3 4 3 0]
   [1 3 3 1]
   [3 3 1 1]]

  [[4 0 4 2]
   [4 3 0 1]
   [3 3 1 4]
   [3 1 1 2]]

  [[0 4 2 4]
   [3 0 1 4]
   [3 1 4 0]
   [1 1 2 4]]

  [[4 2 4 3]
