In [1]:
import numpy as np
arr1=np.zeros(shape=(10,10),dtype=np.int8)
arr1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [2]:
arr2=np.ones(shape=(8,8))
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [3]:
arr3=np.full(shape=(7,9),fill_value=100)
arr3

array([[100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [4]:
arr4=np.random.randint(1,100,size=(5,6))
arr4

array([[42, 55,  5, 13, 17,  7],
       [88, 13, 10, 89, 72, 25],
       [ 2, 93, 80, 30,  1, 66],
       [59, 80, 92, 59, 82, 33],
       [99, 17, 75, 16, 97, 38]])

In [5]:
arr5=np.random.rand(5,6)
arr5

array([[0.87432802, 0.07709908, 0.31855456, 0.94321883, 0.95951612,
        0.42511384],
       [0.77168101, 0.60959329, 0.97458918, 0.5605672 , 0.37923127,
        0.38165283],
       [0.58701376, 0.88861795, 0.84666494, 0.47437586, 0.48793035,
        0.08669858],
       [0.90613199, 0.40038255, 0.90279397, 0.70379753, 0.46370913,
        0.44844533],
       [0.9229855 , 0.29935589, 0.93894418, 0.59928913, 0.13955148,
        0.32133474]])

In [6]:
arr6=np.random.normal(loc=175,scale=10,size=(3,5))
arr6

array([[172.0732986 , 158.55112862, 175.08201993, 175.45178868,
        178.09609837],
       [184.13243458, 172.90829691, 176.28474896, 174.85050594,
        162.6674744 ],
       [172.79443553, 162.16588912, 162.46038469, 179.32600549,
        191.44558622]])

In [7]:
arr7=np.linspace(2,10,4,dtype=np.int0)
arr7

array([ 2,  4,  7, 10], dtype=int64)

In [8]:
arr8=np.eye(10)
arr8

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
arr9=np.logspace(-2,4,10)
arr9

array([1.00000000e-02, 4.64158883e-02, 2.15443469e-01, 1.00000000e+00,
       4.64158883e+00, 2.15443469e+01, 1.00000000e+02, 4.64158883e+02,
       2.15443469e+03, 1.00000000e+04])