In [1]:
import numpy as np
a1=['张','李','陈','刘','赵','王','钱']
a=np.random.choice(a1,size=3,replace=False)
np.disp(a)
np.random.shuffle(a1)
print(a1)
b=np.random.uniform(low=2,high=4,size=(3,4))
np.disp(b)

['王' '刘' '李']
['张', '钱', '陈', '李', '王', '刘', '赵']
[[3.88605548 2.82409505 2.40367303 2.93641246]
 [2.31961297 2.2158543  2.87456493 3.30193984]
 [2.00748652 3.72020117 3.88446532 2.57354313]]


In [3]:
import numpy as np
a1=np.arange(1,13)
print(a1,a1.ndim)
a2=a1.reshape(3,4)
print(a2,a2.ndim)
b2=np.eye(3,4).astype(np.int)
print(b2)
c1=np.concatenate((a2,b2))
print(c1)
c2=np.hstack((a2,b2))
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 2
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  0  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]]
[[ 1  2  3  4  1  0  0  0]
 [ 5  6  7  8  0  1  0  0]
 [ 9 10 11 12  0  0  1  0]]


In [4]:
d=np.split(c2,indices_or_sections=3)
print(d)
b3=b2.transpose((1,0))
print(b3)
a22=a2.T
print(a22)
a23=a2.swapaxes(0,1)
print(a23)

[array([[1, 2, 3, 4, 1, 0, 0, 0]]), array([[5, 6, 7, 8, 0, 1, 0, 0]]), array([[ 9, 10, 11, 12,  0,  0,  1,  0]])]
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
