In [1]:
import numpy as np

In [2]:
arr1=np.random.randn(3,4)
print('arr1:\n',arr1)
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('arr2:',arr2)

arr1:
 [[-0.42352443  1.56693682  1.68810793 -0.50530955]
 [ 1.70922465 -0.11319597 -0.85202013 -0.14960096]
 [-0.60683474 -0.90100207 -1.27956556  0.00645359]]
arr2: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
print('arr1+arr1:\n',arr1+arr2)
print('arr1-arr1:\n',arr1-arr2)
print('arr2*10:\n',arr2*10)
print('arr2*arr2:\n',arr2*arr2)
print('arr2/2:\n',arr2/2)
print('arr2**2:\n',arr2**2)

arr1+arr1:
 [[ 0.57647557  3.56693682  4.68810793  3.49469045]
 [ 6.70922465  5.88680403  6.14797987  7.85039904]
 [ 8.39316526  9.09899793  9.72043444 12.00645359]]
arr1-arr1:
 [[ -1.42352443  -0.43306318  -1.31189207  -4.50530955]
 [ -3.29077535  -6.11319597  -7.85202013  -8.14960096]
 [ -9.60683474 -10.90100207 -12.27956556 -11.99354641]]
arr2*10:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
arr2*arr2:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
arr2/2:
 [[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]]
arr2**2:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [4]:
temp1=arr2[1][2]
print(temp1)

7


In [5]:
arr2[1][2]=1
print(arr2[1][2])

1


In [6]:
temp2=arr2[1:3]
print(temp1)

7


In [7]:
print(arr2[1])

[5 6 1 8]


In [8]:
a2=np.zeros((10,10))
np.disp(a2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
a3=np.eye(8)
print(a3)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [10]:
a5=np.ones((7,8),dtype=np.int8)
print(a5)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [11]:
a6=np.full((50,50),100)
np.disp(a6)

[[100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]
 ...
 [100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]]


In [12]:
ls=[np.arange(0,10)]
a=np.array(ls*10)
a.reshape(10,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
a[[0,9]]=1
a[:,[0,9]]=1
print(a)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 2 3 4 5 6 7 8 1]
 [1 1 2 3 4 5 6 7 8 1]
 [1 1 2 3 4 5 6 7 8 1]
 [1 1 2 3 4 5 6 7 8 1]
 [1 1 2 3 4 5 6 7 8 1]
 [1 1 2 3 4 5 6 7 8 1]
 [1 1 2 3 4 5 6 7 8 1]
 [1 1 2 3 4 5 6 7 8 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [14]:
np.disp(a[1:3])

[[1 1 2 3 4 5 6 7 8 1]
 [1 1 2 3 4 5 6 7 8 1]]


In [15]:
np.disp(a[:,3:6])

[[1 1 1]
 [3 4 5]
 [3 4 5]
 [3 4 5]
 [3 4 5]
 [3 4 5]
 [3 4 5]
 [3 4 5]
 [3 4 5]
 [1 1 1]]


In [16]:
np.disp(a[8])
np.disp(a[np.ix_([8])])

[1 1 2 3 4 5 6 7 8 1]
[[1 1 2 3 4 5 6 7 8 1]]


In [17]:
np.disp(a[:,[8]])

[[1]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [1]]


In [21]:
c=np.full(shape=(3,4,5),fill_value=3.14)
st="此数组的维数： "+str(c.ndim)+"\n总个数: "+str(c.size)+"\n形状: "+str(c.shape)+"\n所占字节数: "+str(c.nbytes)
np.disp(st)
nd4=np.random.normal(loc=175,scale=10,size=(3,5))
np.disp(nd4)
st2="此数组的维数： "+str(nd4.ndim)+"\n内存信息： "+str(nd4.flags)
print(st2)

此数组的维数： 3
总个数: 60
形状: (3, 4, 5)
所占字节数: 480
[[198.90983625 178.37422032 168.03564143 185.34301074 164.47171741]
 [153.81533621 179.28177013 160.22202069 187.26144299 166.50962129]
 [181.57261511 190.36822919 183.08138949 178.68434174 168.03781147]]
此数组的维数： 2
内存信息：   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [22]:
a=np.arange(25)
a=a.reshape((5,5))
print(a)
b=np.array([5,4,3,2,1]*5)
b=b.reshape((5,5))
np.disp(b)
print("数组a+数组b的结果为： ")
np.disp(np.add(a,b))
print("数组b中所有元素求平方： ")
np.disp(b**2)
print("数组a*数组b的结果为： ")
np.disp(np.multiply(a,b))
print("数组a中所有元素之和：")
np.disp(a.sum())
print("数组a中所有元素按列求和： ")
np.disp(np.sum(a,axis=0))
print("数组a中所有元素累加求和： ")
np.disp(np.cumsum(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[5 4 3 2 1]
 [5 4 3 2 1]
 [5 4 3 2 1]
 [5 4 3 2 1]
 [5 4 3 2 1]]
数组a+数组b的结果为： 
[[ 5  5  5  5  5]
 [10 10 10 10 10]
 [15 15 15 15 15]
 [20 20 20 20 20]
 [25 25 25 25 25]]
数组b中所有元素求平方： 
[[25 16  9  4  1]
 [25 16  9  4  1]
 [25 16  9  4  1]
 [25 16  9  4  1]
 [25 16  9  4  1]]
数组a*数组b的结果为： 
[[  0   4   6   6   4]
 [ 25  24  21  16   9]
 [ 50  44  36  26  14]
 [ 75  64  51  36  19]
 [100  84  66  46  24]]
数组a中所有元素之和：
300
数组a中所有元素按列求和： 
[50 55 60 65 70]
数组a中所有元素累加求和： 
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190 210 231 253 276 300]
